Add in basic but functional search history
ABI-Software/map-sidebar pull request #62
Opened 2023-10-20 01:18 UTC by Tehsurfer

2023-10-30 03:03 UTC, alan-wu requested changes
Is it possible to add a popup showing the facets for each of the tag/search result?
I can have multiple heart results with different facets but I cannot tell them apart.

2023-10-30 03:03 UTC, alan-wu commented on src/components/SearchHistory.vue
> +      v-if="reversedSearchHistory.length > 6"
It is also confusing to have the select showing a search term that is not currently active when I am doing a new search using the search input.

2023-10-30 03:03 UTC, alan-wu commented on src/components/SearchHistory.vue
> +        v-for="(item, i) in cascaderOptions"
I think a customised autocomplete in the search input may work better.

2023-10-31 01:59 UTC, Tehsurfer commented on src/components/SearchHistory.vue
> +        v-for="(item, i) in cascaderOptions"
I have removed the filters.

For autocomplete, i will create another version and send it to dominic (he asked for this design)

2023-10-31 02:00 UTC, Tehsurfer commented on src/components/SearchHistory.vue
> +      v-if="reversedSearchHistory.length > 6"
Will reset the placeholder and always show the select box

2023-10-31 02:35 UTC, Tehsurfer commented on src/components/SearchHistory.vue
> +        v-for="(item, i) in cascaderOptions"
@alan-wu autocomplete is here:

https://github.com/ABI-Software/map-sidebar/pull/65

2023-10-31 02:36 UTC, Tehsurfer commented on src/components/SearchHistory.vue
> +        v-for="(item, i) in cascaderOptions"
I asked Dominic if that is better

2023-11-03 00:54 UTC, merged