PMR results mixed
ABI-Software/map-sidebar pull request #81
Opened 2024-07-22 22:39 UTC by akhuoa

This PR is for the replacement of https://github.com/ABI-Software/map-sidebar/pull/80.
Plus, "Flatmap" and "Simulation" buttons in the PMR card.

2024-07-31 03:20 UTC, alan-wu requested changes
Mostly looks good to me, need some minor adjustment.

2024-07-31 07:23 UTC, akhuoa commented on src/components/SidebarContent.vue
> +  noPMRResultsFlag: false,
These variable names are updated in [d639b0e](https://github.com/ABI-Software/map-sidebar/pull/81/commits/d639b0ec1fe7777c67a7cc4ddfb73747c9c19ad5) and [a3195d1](https://github.com/ABI-Software/map-sidebar/pull/81/commits/a3195d1327a1b6d7ab2c2adeeaa512b4e9461962).

2024-07-31 07:24 UTC, akhuoa commented on src/algolia/algolia.js
> +  search(filter, query = '', offset = 0, length = 8) {
This is fixed in [a41e0d0](https://github.com/ABI-Software/map-sidebar/pull/81/commits/a41e0d0d90b43b883a13da8684185265d9390fe1).

2024-07-31 07:24 UTC, akhuoa commented on src/algolia/algolia.js
> +    console.log('searching', filter, query, offset, length)
This console log is removed in [2043bb4](https://github.com/ABI-Software/map-sidebar/pull/81/commits/2043bb48ed0ef1ca7bb4213f591b773afef77eda).

2025-03-02 22:08 UTC, alan-wu commented
Thanks Aung for the pull request, I have opened a new branch and have it caught up with the latest changes - https://github.com/ABI-Software/map-sidebar/tree/pmr_results_mixed
I will close this pull request.

2025-03-02 22:08 UTC, closed without merging